# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.5"
  - "3.4"
  - "2.7"


env:
  - DJANGO_VERSION=1.9
  - DJANGO_VERSION=1.8

before_install:
  - pip install coveralls

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: 
  - pip install -q Django==$DJANGO_VERSION
  - pip install -r requirements/test.txt

# command to run tests using coverage, e.g. python setup.py test
script: 
  - flake8 permabots tests
  - coverage run --source permabots runtests.py

after_success:
  - coveralls
